/*
# Onam Gift Exchange Platform Schema

1. Overview
   Multi-user platform for organizing secret gift exchanges during Onam.
   Users sign in with email/password. Each user owns their events, participations, wishlists, and assignments.

2. New Tables
   - `profiles`: extended user info (display name, avatar, phone, language, accessibility prefs)
   - `events`: gift exchange events (name, description, date, venue, category, visibility, budget range, currency, banner color)
   - `participants`: join table between events and users (status, joined_at)
   - `wishlists`: gift preferences per participant (brand, color, hobbies, size, allergies, notes)
   - `assignments`: secret santa assignments (giver -> receiver, generated by organizer)
   - `gift_tracking`: status of gift from purchase to delivery
   - `memory_wall_posts`: photos and memories shared in an event
   - `leaderboard_entries`: gamification points per participant
   - `notifications`: in-app notifications for users

3. Security
   - RLS enabled on every table.
   - Profiles: owner-scoped CRUD.
   - Events: owner can CRUD; participants can SELECT events they joined; public events visible to all authenticated.
   - Participants: event organizer can insert/update/delete; participants can SELECT.
   - Wishlists: owner-scoped; event organizer and assigned giver can read.
   - Assignments: only the giver and the event organizer can see.
   - Gift tracking: giver and organizer can update/read.
   - Memory wall: event participants can read; post author can delete.
   - Leaderboard: readable by event participants.
   - Notifications: owner-scoped.
*/

-- ===== TABLES FIRST =====

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text NOT NULL DEFAULT '',
  avatar_url text,
  phone text,
  preferred_language text DEFAULT 'en',
  high_contrast boolean DEFAULT false,
  font_size text DEFAULT 'medium',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organizer_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  event_date date NOT NULL,
  event_time text,
  venue text,
  category text DEFAULT 'family',
  visibility text DEFAULT 'private',
  min_budget numeric DEFAULT 0,
  max_budget numeric DEFAULT 100,
  currency text DEFAULT 'INR',
  banner_color text DEFAULT '#d4a017',
  invite_code text UNIQUE,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  status text DEFAULT 'pending',
  joined_at timestamptz DEFAULT now(),
  UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  giver_user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE (event_id, giver_user_id),
  UNIQUE (event_id, receiver_user_id)
);

CREATE TABLE IF NOT EXISTS wishlists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  participant_id uuid NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  favorite_brands text,
  favorite_colors text,
  hobbies text,
  clothing_size text,
  allergies text,
  custom_notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gift_tracking (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  giver_user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  status text DEFAULT 'not_started',
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memory_wall_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  title text,
  image_url text,
  caption text,
  likes integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS leaderboard_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  points integer DEFAULT 0,
  badge text,
  UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  event_id uuid REFERENCES events(id) ON DELETE CASCADE,
  message text NOT NULL,
  type text DEFAULT 'info',
  read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- ===== ENABLE RLS =====

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_wall_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- ===== POLICIES =====

-- Profiles
DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT TO authenticated USING (auth.uid() = id);
DROP POLICY IF EXISTS "insert_own_profile" ON profiles;
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Events
DROP POLICY IF EXISTS "select_events" ON events;
CREATE POLICY "select_events" ON events FOR SELECT TO authenticated USING (
  organizer_id = auth.uid()
  OR visibility = 'public'
  OR EXISTS (SELECT 1 FROM participants p WHERE p.event_id = events.id AND p.user_id = auth.uid())
);
DROP POLICY IF EXISTS "insert_events" ON events;
CREATE POLICY "insert_events" ON events FOR INSERT TO authenticated WITH CHECK (organizer_id = auth.uid());
DROP POLICY IF EXISTS "update_events" ON events;
CREATE POLICY "update_events" ON events FOR UPDATE TO authenticated USING (organizer_id = auth.uid()) WITH CHECK (organizer_id = auth.uid());
DROP POLICY IF EXISTS "delete_events" ON events;
CREATE POLICY "delete_events" ON events FOR DELETE TO authenticated USING (organizer_id = auth.uid());

-- Participants
DROP POLICY IF EXISTS "select_participants" ON participants;
CREATE POLICY "select_participants" ON participants FOR SELECT TO authenticated USING (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = participants.event_id AND e.organizer_id = auth.uid())
  OR EXISTS (
    SELECT 1 FROM participants p2
    WHERE p2.event_id = participants.event_id AND p2.user_id = auth.uid()
  )
);
DROP POLICY IF EXISTS "insert_participants" ON participants;
CREATE POLICY "insert_participants" ON participants FOR INSERT TO authenticated WITH CHECK (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = participants.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "update_participants" ON participants;
CREATE POLICY "update_participants" ON participants FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM events e WHERE e.id = participants.event_id AND e.organizer_id = auth.uid())
) WITH CHECK (
  EXISTS (SELECT 1 FROM events e WHERE e.id = participants.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "delete_participants" ON participants;
CREATE POLICY "delete_participants" ON participants FOR DELETE TO authenticated USING (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = participants.event_id AND e.organizer_id = auth.uid())
);

-- Assignments
DROP POLICY IF EXISTS "select_assignments" ON assignments;
CREATE POLICY "select_assignments" ON assignments FOR SELECT TO authenticated USING (
  giver_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = assignments.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "insert_assignments" ON assignments;
CREATE POLICY "insert_assignments" ON assignments FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM events e WHERE e.id = assignments.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "delete_assignments" ON assignments;
CREATE POLICY "delete_assignments" ON assignments FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM events e WHERE e.id = assignments.event_id AND e.organizer_id = auth.uid())
);

-- Wishlists
DROP POLICY IF EXISTS "select_wishlists" ON wishlists;
CREATE POLICY "select_wishlists" ON wishlists FOR SELECT TO authenticated USING (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = wishlists.event_id AND e.organizer_id = auth.uid())
  OR EXISTS (SELECT 1 FROM assignments a WHERE a.giver_user_id = auth.uid() AND a.event_id = wishlists.event_id AND a.receiver_user_id = wishlists.user_id)
);
DROP POLICY IF EXISTS "insert_wishlists" ON wishlists;
CREATE POLICY "insert_wishlists" ON wishlists FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "update_wishlists" ON wishlists;
CREATE POLICY "update_wishlists" ON wishlists FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "delete_wishlists" ON wishlists;
CREATE POLICY "delete_wishlists" ON wishlists FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Gift tracking
DROP POLICY IF EXISTS "select_gift_tracking" ON gift_tracking;
CREATE POLICY "select_gift_tracking" ON gift_tracking FOR SELECT TO authenticated USING (
  giver_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = gift_tracking.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "insert_gift_tracking" ON gift_tracking;
CREATE POLICY "insert_gift_tracking" ON gift_tracking FOR INSERT TO authenticated WITH CHECK (
  giver_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = gift_tracking.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "update_gift_tracking" ON gift_tracking;
CREATE POLICY "update_gift_tracking" ON gift_tracking FOR UPDATE TO authenticated USING (
  giver_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = gift_tracking.event_id AND e.organizer_id = auth.uid())
) WITH CHECK (
  giver_user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = gift_tracking.event_id AND e.organizer_id = auth.uid())
);

-- Memory wall posts
DROP POLICY IF EXISTS "select_memory_posts" ON memory_wall_posts;
CREATE POLICY "select_memory_posts" ON memory_wall_posts FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM participants p WHERE p.event_id = memory_wall_posts.event_id AND p.user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = memory_wall_posts.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "insert_memory_posts" ON memory_wall_posts;
CREATE POLICY "insert_memory_posts" ON memory_wall_posts FOR INSERT TO authenticated WITH CHECK (
  user_id = auth.uid()
  AND EXISTS (SELECT 1 FROM participants p WHERE p.event_id = memory_wall_posts.event_id AND p.user_id = auth.uid())
);
DROP POLICY IF EXISTS "delete_memory_posts" ON memory_wall_posts;
CREATE POLICY "delete_memory_posts" ON memory_wall_posts FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Leaderboard entries
DROP POLICY IF EXISTS "select_leaderboard" ON leaderboard_entries;
CREATE POLICY "select_leaderboard" ON leaderboard_entries FOR SELECT TO authenticated USING (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM participants p WHERE p.event_id = leaderboard_entries.event_id AND p.user_id = auth.uid())
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = leaderboard_entries.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "insert_leaderboard" ON leaderboard_entries;
CREATE POLICY "insert_leaderboard" ON leaderboard_entries FOR INSERT TO authenticated WITH CHECK (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = leaderboard_entries.event_id AND e.organizer_id = auth.uid())
);
DROP POLICY IF EXISTS "update_leaderboard" ON leaderboard_entries;
CREATE POLICY "update_leaderboard" ON leaderboard_entries FOR UPDATE TO authenticated USING (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = leaderboard_entries.event_id AND e.organizer_id = auth.uid())
) WITH CHECK (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM events e WHERE e.id = leaderboard_entries.event_id AND e.organizer_id = auth.uid())
);

-- Notifications
DROP POLICY IF EXISTS "select_notifications" ON notifications;
CREATE POLICY "select_notifications" ON notifications FOR SELECT TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS "insert_notifications" ON notifications;
CREATE POLICY "insert_notifications" ON notifications FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "update_notifications" ON notifications;
CREATE POLICY "update_notifications" ON notifications FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
DROP POLICY IF EXISTS "delete_notifications" ON notifications;
CREATE POLICY "delete_notifications" ON notifications FOR DELETE TO authenticated USING (user_id = auth.uid());

-- ===== INDEXES =====

CREATE INDEX IF NOT EXISTS idx_events_organizer ON events(organizer_id);
CREATE INDEX IF NOT EXISTS idx_participants_event ON participants(event_id);
CREATE INDEX IF NOT EXISTS idx_participants_user ON participants(user_id);
CREATE INDEX IF NOT EXISTS idx_assignments_event ON assignments(event_id);
CREATE INDEX IF NOT EXISTS idx_assignments_giver ON assignments(giver_user_id);
CREATE INDEX IF NOT EXISTS idx_gift_tracking_assignment ON gift_tracking(assignment_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_memory_event ON memory_wall_posts(event_id);
CREATE INDEX IF NOT EXISTS idx_leaderboard_event ON leaderboard_entries(event_id);

-- ===== AUTO-CREATE PROFILE ON SIGNUP =====

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
